### ISSUE TITLE
[main/WARN]: Error loading class: cn/enaium/cf4m/event/events/UpdateEvent (java.lang.ClassNotFoundException: cn/enaium/cf4m/event/events/UpdateEvent)

### ISSUE THREAD

**Issue by AstroOrbis** [cf4m/cf4m-fabric#1]
I keep getting this error in my latest.log:
[main/WARN]: Error loading class: cn/enaium/cf4m/event/events/UpdateEvent (java.lang.ClassNotFoundException: cn/enaium/cf4m/event/events/UpdateEvent)

**Comment by Enaium** [comment]
The new version removes this
